@hostname = localhost
@port = {{$dotenv PORT}}
@host = {{hostname}}:{{port}}
@contentType = application/json

###

# @name getUsers
GET http://{{host}}/users HTTP/1.1

###
# @prompt role Role of the users to get

# @name getUsersByRole
GET http://{{host}}/users?role={{role}} HTTP/1.1

###
# @prompt userId Id of the user to get

# @name getUser
GET http://{{host}}/users/{{userId}} HTTP/1.1

###

# @name createUser
POST http://{{host}}/users HTTP/1.1
Content-Type: {{contentType}}

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "admin@example.com",
  "role": "admin",
  "dateOfBirth": "1990-01-01",
  "placeOfBirth": "Split, Croatia",
  "citizenship": "Croatian",
  "pinOIB": "01234567892",
  "idCardNumber": "01234567892",
  "address": "Example Street 1, 21000 Split, Croatia",
  "contactNumber": "+38512345678",
  "semester": "0",
  "yearOfStudy": "0"
}

###
# @prompt userId Id of the user to update

# @name updateUser
PUT http://{{host}}/users/{{userId}} HTTP/1.1
Content-Type: {{contentType}}

{
  "semester": "2",
  "yearOfStudy": "2"
}

###
# @prompt userId Id of the user to change password

# @name changePassword

PUT http://{{host}}/users/{{userId}}/change-password HTTP/1.1
Content-Type: {{contentType}}

{
  "oldPassword": "Password123!",
  "newPassword": "Password456!",
  "confirmNewPassword": "Password456!"
}


###
# @prompt userId Id of the user to delete

# @name deleteUser
DELETE http://{{host}}/users/{{userId}} HTTP/1.1
